basket/urls.py
from django.urls import path
from . import views

app_name = "basket"
urlpatterns = [
    path("add/", views.add_to_basket, name="add_to_basket"),
    path("", views.view_basket, name="view_basket"),
    path("remove/<int:variant_id>/", views.remove_from_basket, name="remove"),
    path("update/", views.update_quantity, name="update"),
]

happy_tails/urls.py
from django.contrib import admin
from django.urls import path, include
from checkout import views as checkout_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("basket/", include("basket.urls")),
    path("checkout/", include("checkout.urls")),
    path("accounts/", include("allauth.urls")),
    path("profile/", include("profiles.urls", namespace="profiles")),
    path("", include(("store.urls", "store"), namespace="store")),
]

profiles/urls.py
from django.urls import path
from . import views

app_name = "profiles"

urlpatterns = [
    path("", views.profile, name="profile"),
    path("edit/", views.profile_edit, name="profile_edit"),

    path("addresses/add/", views.address_add, name="address_add"),
    path("addresses/<int:pk>/edit/", views.address_edit, name="address_edit"),
    path("addresses/<int:pk>/delete/", views.address_delete, name="address_delete"),
]

store/urls.py
from django.urls import path
from . import views

app_name = "store"

urlpatterns = [
    path(
        "",
        views.product_list,
        name="product_list"
        ),
    path(
        "",
        views.product_list,
        name="home"
        ),
    path(
        "category/<slug:category_slug>/",
        views.product_list,
        name="category"
        ),
    path(
        "products/",
        views.product_list),
    path(
        "products/<slug:slug>/",
        views.product_detail,
        name="product_detail"
        ),

    path(
        "manage/catalog/",
        views.manage_dashboard,
        name="manage_dashboard"
        ),
    path(
        "manage/products/new/",
        views.product_create, name="product_create"
        ),
    path(
        "manage/products/<int:pk>/edit/",
        views.product_edit, name="product_edit"
        ),
    path(
        "manage/products/<int:pk>/delete/",
        views.product_delete, name="product_delete"
        ),
]

templates/includes/footer.html
<footer class=" text-center fixed-bottom">
    <p> &copy; {{ year|default:"2025" }} Happy Tails Pet Supplies</p>
    <p class="mb-0">
        Created by <a href="https://github.com/TheRealMcCall/" target="_blank"
            aria-label="Visit Luke McCall's GitHub profile">Luke McCall</a>
    </p>
</footer>

templates/includes/header.html
<header>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'store:home' %}">
                <h1 class="h4 mb-0">Happy Tails Pet Supplies</h1>
            </a>

            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">

                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'store:home' %}">Home</a>
                    </li>

                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'profiles:profile' %}">My Account</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_logout' %}">Logout</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_login' %}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_signup' %}">Register</a>
                    </li>
                    {% endif %}

                    {% if request.user.is_staff %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'store:manage_dashboard' %}">Product Management</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/admin/">Admin</a>
                    </li>
                    {% endif %}

                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'basket:view_basket' %}">Basket</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>